# Generated by Django 2.2.5 on 2020-02-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200215_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bathrooms',
            new_name='bedrooms',
        ),
    ]
